"""Send real emails for complaint escalation and response letters."""
import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)

_SMTP_HOST = "smtp.gmail.com"
_SMTP_PORT = 587


def _get_credentials() -> tuple[str, str] | None:
    addr = os.getenv("EMAIL_ADDRESS", "")
    pwd = os.getenv("EMAIL_APP_PASSWORD", "")
    if not addr or not pwd:
        return None
    return addr, pwd


def _send(to_address: str, subject: str, html_body: str) -> bool:
    """Send an HTML email. Returns True on success."""
    creds = _get_credentials()
    if not creds:
        logger.info(
            "[EMAIL] Email sending not configured. Set EMAIL_ADDRESS and EMAIL_APP_PASSWORD in .env"
        )
        logger.info("[EMAIL] Draft subject: %s → %s", subject, to_address)
        return False

    from_addr, password = creds
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to_address
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(_SMTP_HOST, _SMTP_PORT) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.login(from_addr, password)
            smtp.sendmail(from_addr, to_address, msg.as_string())
        logger.info("[EMAIL] Sent '%s' to %s", subject, to_address)
        return True
    except Exception as exc:
        logger.error("[EMAIL] Failed to send '%s': %s", subject, exc)
        return False


def send_resolution_email(
    to_address: str,
    subject: str,
    letter_text: str,
    complaint_summary: dict,
) -> bool:
    """Send the customer response letter as a professionally formatted HTML email."""
    product = complaint_summary.get("product", "Financial Product")
    complaint_id = complaint_summary.get("complaint_id", "N/A")
    regulations = complaint_summary.get("applicable_regulations", [])
    reg_badges = "".join(
        f'<span style="display:inline-block;padding:2px 8px;margin:2px;border-radius:12px;'
        f'background:#dbeafe;color:#1e40af;font-size:11px;font-weight:600;">{r}</span>'
        for r in regulations
    )

    letter_html = letter_text.replace("\n", "<br>")

    html = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family:Arial,sans-serif;background:#f9fafb;margin:0;padding:20px;">
      <div style="max-width:600px;margin:0 auto;background:#fff;border-radius:8px;
                  border:1px solid #e5e7eb;overflow:hidden;">
        <div style="background:#059669;padding:20px 24px;">
          <h2 style="color:#fff;margin:0;font-size:18px;">CFPB Complaint Intelligence System</h2>
          <p style="color:#d1fae5;margin:4px 0 0;font-size:13px;">
            Complaint Resolution — {product}
          </p>
        </div>
        <div style="padding:24px;">
          <p style="font-size:12px;color:#6b7280;">Complaint ID: <strong>{complaint_id}</strong></p>
          <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:6px;
                      padding:16px;margin:16px 0;line-height:1.7;font-size:14px;color:#111827;">
            {letter_html}
          </div>
          {f'<div style="margin-top:12px;"><p style="font-size:11px;color:#6b7280;margin-bottom:4px;">Applicable Regulations:</p>{reg_badges}</div>' if reg_badges else ""}
        </div>
        <div style="padding:12px 24px;background:#f9fafb;border-top:1px solid #e5e7eb;">
          <p style="font-size:11px;color:#9ca3af;margin:0;">
            Generated by CFPB Complaint Intelligence System — UMD Agentic AI Challenge 2026
          </p>
        </div>
      </div>
    </body>
    </html>
    """

    full_subject = subject or f"CFPB Complaint Resolution — {product} — {complaint_id}"
    return _send(to_address, full_subject, html)


def send_escalation_email(
    to_address: str,
    complaint_summary: dict,
    risk_analysis: dict,
) -> bool:
    """Send escalation notification to the compliance officer."""
    product = complaint_summary.get("product", "Unknown")
    complaint_id = complaint_summary.get("complaint_id", "N/A")
    risk_gap = risk_analysis.get("risk_gap", 0.0)
    severity = complaint_summary.get("severity", "unknown")
    narrative_preview = (complaint_summary.get("narrative_preview", "") or "")[:300]
    team = complaint_summary.get("assigned_team", "N/A")

    risk_pct = round(risk_gap * 100, 1)
    severity_color = {"critical": "#dc2626", "high": "#d97706", "medium": "#2563eb"}.get(
        severity, "#6b7280"
    )

    html = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family:Arial,sans-serif;background:#f9fafb;margin:0;padding:20px;">
      <div style="max-width:600px;margin:0 auto;background:#fff;border-radius:8px;
                  border:1px solid #e5e7eb;overflow:hidden;">
        <div style="background:#dc2626;padding:20px 24px;">
          <h2 style="color:#fff;margin:0;font-size:18px;">⚠️ High-Risk Complaint Escalation</h2>
          <p style="color:#fecaca;margin:4px 0 0;font-size:13px;">
            Immediate compliance review required
          </p>
        </div>
        <div style="padding:24px;">
          <table style="width:100%;border-collapse:collapse;margin-bottom:16px;">
            <tr>
              <td style="padding:8px 0;font-size:13px;color:#6b7280;">Complaint ID:</td>
              <td style="padding:8px 0;font-size:13px;font-weight:600;">{complaint_id}</td>
            </tr>
            <tr>
              <td style="padding:8px 0;font-size:13px;color:#6b7280;">Product:</td>
              <td style="padding:8px 0;font-size:13px;font-weight:600;">{product}</td>
            </tr>
            <tr>
              <td style="padding:8px 0;font-size:13px;color:#6b7280;">Severity:</td>
              <td style="padding:8px 0;">
                <span style="padding:2px 8px;border-radius:12px;font-size:12px;font-weight:600;
                             background:{severity_color}22;color:{severity_color};">
                  {severity.upper()}
                </span>
              </td>
            </tr>
            <tr>
              <td style="padding:8px 0;font-size:13px;color:#6b7280;">Risk Gap:</td>
              <td style="padding:8px 0;font-size:13px;font-weight:600;color:#dc2626;">
                {risk_pct}% above baseline
              </td>
            </tr>
            <tr>
              <td style="padding:8px 0;font-size:13px;color:#6b7280;">Routed To:</td>
              <td style="padding:8px 0;font-size:13px;font-weight:600;">{team}</td>
            </tr>
          </table>
          <div style="background:#fff7f7;border:1px solid #fecaca;border-radius:6px;padding:12px;">
            <p style="font-size:12px;color:#6b7280;margin:0 0 6px;">Complaint Excerpt:</p>
            <p style="font-size:13px;color:#111827;margin:0;line-height:1.6;">
              {narrative_preview}{'...' if len(narrative_preview) == 300 else ''}
            </p>
          </div>
          <div style="margin-top:16px;padding:12px;background:#fef3c7;border-radius:6px;
                      border:1px solid #fde68a;">
            <p style="font-size:13px;color:#92400e;margin:0;">
              <strong>Action Required:</strong> This complaint has been automatically escalated
              due to its risk profile. Please review and take appropriate compliance action.
            </p>
          </div>
        </div>
        <div style="padding:12px 24px;background:#f9fafb;border-top:1px solid #e5e7eb;">
          <p style="font-size:11px;color:#9ca3af;margin:0;">
            CFPB Complaint Intelligence System — UMD Agentic AI Challenge 2026
          </p>
        </div>
      </div>
    </body>
    </html>
    """

    subject = f"⚠️ High-Risk Complaint Escalation — {product} — Risk Gap: {risk_pct}%"
    return _send(to_address, subject, html)
